"""Dictionary remove field.

Revision ID: a14af22c991a
Revises: 25d8c5b60dad
Create Date: 2021-05-30 17:18:49.072263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14af22c991a'
down_revision = '25d8c5b60dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionary', 'total_practice_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('total_practice_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
